### ISSUE TITLE
NUGET.EXE not found.

### ISSUE THREAD

**Issue by NafissaBHJ** [woodemi/quick.flutter#80]
After adding quick_notify in pubscpec.yaml and run app I get : 
CMake Error at flutter/ephemeral/.plugin_symlinks/quick_notify/windows/CMakeLists.txt:13 (message):
  Please install this executable, and run CMake again.

**Comment by Sunbreak** [comment]
https://github.com/microsoft/winget-pkgs/issues/17533#issuecomment-1304383597

```sh
> winget install NuGet
```
